-- Select role to create warehouse, database, schema, role, and user
USE ROLE ACCOUNTADMIN;

--Create Warehouse for dbt work
CREATE OR REPLACE WAREHOUSE DBT_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = true
  INITIALLY_SUSPENDED = false;

--Create Database for dbt work
CREATE OR REPLACE DATABASE DBT_DEV_DB;

--Create Schema for dbt work
CREATE OR REPLACE SCHEMA "DBT_DEV_DB"."JM";

--Create Role for dbt work
CREATE OR REPLACE ROLE "DBT_ROLE";

--Create User for dbt work
CREATE OR REPLACE USER DBT_USER PASSWORD = 'dbtuser' 
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE = DBT_WH 
  DEFAULT_ROLE = DBT_ROLE;

--Grant Permissions to dbt user
GRANT ROLE "DBT_ROLE" TO ROLE "SYSADMIN";
GRANT ROLE "DBT_ROLE" TO USER "DBT_USER";

--Grant Permissions to dbt role
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE "DBT_DEV_DB" TO DBT_ROLE;
GRANT ALL ON SCHEMA "DBT_DEV_DB"."JM" TO DBT_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE "DBT_DEV_DB" TO DBT_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE "DBT_DEV_DB" TO DBT_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE "DBT_DEV_DB" TO DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE "DBT_DEV_DB" TO DBT_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE "DBT_DEV_DB" TO DBT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE "DBT_DEV_DB" TO DBT_ROLE;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE DBT_ROLE;

--Grant Permissions to dbt schema
SHOW GRANTS ON SCHEMA "DBT_DEV_DB"."JM";
SHOW GRANTS TO USER DBT_USER;